### PR TITLE
Add Japanese map `bgnpcgn-jpn-Hrkt-Latn-1930`

### PR DESCRIPTION
**Pull request by chaaklau**
This is for Kana to Hepburn only. Processing of Kanji and word segmentation have not been implemented.

#109

### CODE REVIEW

**Comment by chaaklau** [comment]
Currently there are two Japanese maps in the `maps/` directory with the authority id `mext`
In fact only `mext-jpn-Hrkt-Latn-kunrei` (which has yet to be implemented) is recommended in 1954 ("内閣告示第一号 -- ローマ字のつづり方"). 

The name Hepburn was not even mentioned in the document. The document contains some (but not a complete list) of romanised syllables in Hepburn, and it says in a note that:
> "The spellings listed in Table 2 may be used only in circumstances where international relations and other conventional practices cannot be readily changed. (国際的関係その他従来の慣例をにわかに改めがたい事情にある場合に限り、第2表に掲げたつづり方によつてもさしつかえない。)".

I suggest either 
(a) removing the authority ID from `mext-jpn-Hrkt-Latn-hepburn` and keep this as a historic map; or 
(b) remove `mext-jpn-Hrkt-Latn-hepburn` and move the character mappings to `bgnpcgn-jpn-Hrkt-Latn-1930.yaml`

**Comment by chaaklau** [comment]
Hepburn transliteration used by Ministry of Foreign Affairs of Japan for person names is different system.
https://www.ezairyu.mofa.go.jp/passport/hebon.html

**Comment by ronaldtse** [comment]
a) But "第2表" exists in "内閣告示第一号". Can we find a name for it?

b) `bgnpcgn-jpn-Hrkt-Latn-1930` should not be the definition of Hepburn; we can instead register a separate map for Hepburn based on the original dictionary.

We had a meeting today for ISO/CC 24229 (where the codes are defined), and the `historic` code will change to `var`. We could call the original system `var-jpn-hkrt-latn-hepburn-1886` instead.

> Hepburn transliteration used by Ministry of Foreign Affairs of Japan for person names is different system.

We should register a `mofa-jpn-hkrt-latn-yyyy` where yyyy is the year MOFA adopted this system.

**Comment by chaaklau** [comment]
These are the transliteration systems for Japanese that I am aware of:

**Hepburn**
- `var-jpn-hkrt-latn-hepburn-1886`: Traditional Hepburn
- `mofa-jpn-hkrt-latn-1989`: MOFA, [simplified version of Traditional Hepburn](https://www.ezairyu.mofa.go.jp/passport/hebon.html)
- `var-jpn-hkrt-latn-hepburn-1954`: Modified Hepburn (which is based on Kenkyusha's New Japanese-English Dictionary (3rd edition))
- `bgnpcgn-jpn-hkrt-latn-1976`:   BGN/PCGN 1976 Agreement, a more elaborated version of Modified Hepburn. (Do we have to keep the name `bgnpcgn-jpn-hkrt-latn-1930`?)

**Kunrei**
- `var-jpn-hkrt-latn-nippon`    Nippon-siki, which is an earlier version of Kunrei
- `mext-jpn-hkrt-latn-kunrei`  内閣告示第一号 -- ローマ字のつづり方
- `iso-jpn-hkrt-latn-iso3602`  ISO 3602 Romanization of Japanese (kana script)

(Note: The use of Hepburn romanization was written into law in 1989: [平成元年外務省令第十一号
旅券法施行規則 5.3](https://elaws.e-gov.go.jp/search/elawsSearch/elaws_search/lsg0500/detail?lawId=401M50000020011#50))

**Comment by ronaldtse** [comment]
Got it.

> bgnpcgn-jpn-hkrt-latn-1976: BGN/PCGN 1976 Agreement, a more elaborated version of Modified Hepburn. (Do we have to keep the name bgnpcgn-jpn-hkrt-latn-1930?)

I believe `bgnpcgn-jpn-hkrt-latn-1976` and `bgnpcgn-jpn-hkrt-latn-1930` are different systems, right? If so they should have different codes.

**Comment by chaaklau** [comment]
> I believe bgnpcgn-jpn-hkrt-latn-1976 and bgnpcgn-jpn-hkrt-latn-1930 are different systems, right? If so they should have different codes.

GeoNames database has the code `jpn_Hrkt2Latn_BGN_1930`, but the transliterations follow `bgnpcgn-jpn-hkrt-latn-1976` closely. 
I don't have the specification for `bgnpcgn-jpn-hkrt-latn-1930`.

**Comment by ronaldtse** [comment]
Just read https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693719/ROMANIZATION_OF_JAPANESE_KANA.pdf , I think we can assume that 1976 is identical to 1930 in application of rules. Let's just use the year 1976 for now, will seek clarification.

**Comment by ronaldtse** [comment]
@chaaklau please ping when ready to merge. Thanks!

**Comment by chaaklau** [comment]
These maps have been implemented for Japanese
`var-jpn-hkrt-latn-hepburn-1886`: Traditional Hepburn
`mofa-jpn-hkrt-latn-1989`: MOFA, simplified version of Traditional Hepburn (Passport names)
`var-jpn-hkrt-latn-hepburn-1954`: Modified Hepburn
`bgnpcgn-jpn-hkrt-latn-1976`: BGN/PCGN 1976 Agreement (#109)
`mext-jpn-hkrt-latn-kunrei` 内閣告示第一号 -- ローマ字のつづり方
`iso-jpn-hkrt-latn-iso3602` ISO 3602 Romanization of Japanese (kana script)  (#214)

Nippon-siki has not been implemented. This was designed for pre-WW2 Japanese orthography.
`var-jpn-hkrt-latn-nippon` Nippon-siki, which is an earlier version of Kunrei

@ronaldtse   Can you please check if this can be merged with master?

**Comment by ronaldtse** [comment]
Thank you @chaaklau !

**Pull request merged**
