### PR TITLE
#217 add icao-mul-cyrl-latn-2015

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #217

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse it's a first `mul` transliteration scheme how should we handle language-specific rules, maybe should we implement such feature and allow "override" `language` property in `yaml` config?

### Proposal

Language-specific rules can look like this:
```
    - language: iso-639-2:bel
      pattern: .....
      result: "..."
```

Extend `Interscript.transliterate(system_code, string, maps={})` to `Interscript.transliterate(system_code, string, maps={}, options={})`, and allow key `language` in options

@ronaldtse @AhMohsen46 @andrew2net @antonsviridenko let me know how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP agree, for the “mul” map, it should be coded as “iso-639-3:mul”, and the language specific rules could be either:

1. implemented in separate maps with separate language codes (in separate files), or 
2. we could put those rules inside the “mul” file, but we will need to find a way to keep the information accessible from the map.

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I see we already implemented the first option, we have a list of `map/icao-*` mappings

**Comment by ronaldtse** [comment]
@CAMOBAP Then is your proposal to also allow the second option?

There are indeed systems that are supposed to work with multiple languages, e.g. ISO 9 is supposed to work with 62 languages and splitting it into 62 files is not ideal.

**Comment by CAMOBAP** [comment]
> Then is your proposal to also allow the second option?

I thought that this task created exactly for this approach (single mapping many supported languages) initially, correct me if I'm wrong

**Comment by ronaldtse** [comment]
@CAMOBAP it wasn't but it seems like a good idea 😉

**Comment by CAMOBAP** [comment]
@ronaldtse ok I will update this PR according to the https://github.com/interscript/interscript/pull/570#issuecomment-711034309 above

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

@webdev778 could you have a look on how to port this functionality to the JS side? Please directly commit to this branch. Thanks!

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP ! Finally!!

**Comment by CAMOBAP** [comment]
@ronaldtse not done yet unfortunatelly( but I will deal with it today

**Comment by ronaldtse** [comment]
Closed in favour of https://github.com/interscript/maps/pull/168

**Pull request closed without merging**
