### PR TITLE
Simplify configuration

### PR DESCRIPTION
**Pull request by CAMOBAP**
%80 of out GHA config platform independent I propose to keep it in a single configuration

### CODE REVIEW

**Comment by ronaldtse** [comment]
Agreed, can you update the README as well? Thanks!

**Comment by CAMOBAP** [comment]
> Agreed, can you update the README as well? Thanks!

Surprisingly it's already up-to-date, because initially, we used this approach (with single workflow file) and we did a 'split' relatively recently, so README contains the correct badge

**Comment by CAMOBAP** [comment]
@ronaldtse or you mean something else?

**Comment by ronaldtse** [comment]
All good, thanks!

**Pull request merged**
