### PR TITLE
Add ALA-LC Bengali transliteration system

### PR DESCRIPTION
**Pull request by abunashir**
Extracted from: https://github.com/riboseinc/interoperable-transliteration/pull/34#issuecomment-566846486

cc: @ronaldtse 

### Update: Extending capability

Recently, we came across a use case where we wanted to re-use character mappings from another system, and this lead to the idea that we might wanna add some extending capabilities to a
system mappings.

This commit adds that functionality, and it also keeps this mapping handling separate so if necessary then this would be the only place we will need to update in the future.

### CODE REVIEW

**Comment by abunashir** [comment]
Hey @ronaldtse, I was looking at the letters mapping for this - [ala-lc for benagli](https://www.loc.gov/catdir/cpso/romanization/bengali.pdf), and it looks exactly the same as the one for [un-ben-Beng-Latn](https://github.com/riboseinc/interoperable-transliteration/blob/master/maps/un-ben-Beng-Latn-2016.yaml) mappings.

I'm not sure about the differences between these two systems, but looking at the letters mappings, it seems like they are the same, and the Ligatures will be the same, so the only thing I think we need is to copy over all the rules from UN System. What do you think?

**Comment by ronaldtse** [comment]
@abunashir Interesting!

1. We can consider these identical systems to share the same content.
2. We can duplicate the content.

Approach 2 is probably the easiest. Approach 1 is the best, but we will need to assign a "source", which is the UN system. Maybe from the ALA-LC system definition we can just point it to the UN system code "un-ben-Beng-Latn" ?

**Comment by abunashir** [comment]
Yap, it could be a good idea to share some mappings sometimes, let me see if we can do something similar to inheritance here :)

**Review by ronaldtse — APPROVED** [review]
Very nice. Thanks @abunashir!

**Pull request merged**
