### PR TITLE
odni-pus-Arab-Latn-2011

### PR DESCRIPTION
**Pull request by AhMohsen46**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@AhMohsen46 could you add a "note" that the `"ey" rule comes from clarification in interscript/interscript#509` ? Thanks!

**Comment by ronaldtse** [comment]
@AhMohsen46 is this ready to be merged? The only build failure is a known one, and we can merge if that’s the only failure.

**Comment by AhMohsen46** [comment]
@ronaldtse will add a few tests and merge very soon, very sorry it was not visited in the last 10 days, was very busy on other tasks

**Comment by AhMohsen46** [comment]
this one is done https://github.com/interscript/interscript/issues/617, please @ronaldtse take a look, and merge if you think it's good  to go
Thank you

**Comment by ronaldtse** [comment]
Thank you @AhMohsen46 ! Merging.

**Pull request merged**
