### PR TITLE
Added un-hin-deva-latn-2016 and un-mar-deva-latn-2016

### PR DESCRIPTION
**Pull request by bilashsaha**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@bilashsaha thanks! Could you help rename the filenames so they are case sensitive (the first character of a script code needs to be capitalized, e.g. `latn` => `Latn`)?

**Comment by ronaldtse** [comment]
All passing now except the Windows job anomaly on gem installation. Merging.

**Comment by ronaldtse** [comment]
@bilashsaha I've done the renaming.

**Comment by bilashsaha** [comment]
Thanks @ronaldtse !

**Pull request merged**
