### PR TITLE
Added BGN/PCGN Romanization System -- Nepali (2011)

### PR DESCRIPTION
**Pull request by bilashsaha**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @bilashsaha! Could you:

1. Help double check against the original specification in https://github.com/interscript/interscript/issues/141#issuecomment-687984324
2. Add maybe 10 more examples so we know things work right?

**Comment by bilashsaha** [comment]
@ronaldtse 
 - Done the checking with original spec
-  Added more tests from newspaper.

**Comment by ronaldtse** [comment]
Thanks for the excellent work @bilashsaha ! Merging now.

**Comment by ronaldtse** [comment]
One more thing... @bilashsaha could you help rebase this PR so we can merge smoothly? Thanks.

**Comment by bilashsaha** [comment]
This is closed as [PR](https://github.com/interscript/interscript/pull/385) replacing this one.

**Pull request closed without merging**
