### PR TITLE
bgnpcgn-ara-Arab-Latn-1956 init commit

### PR DESCRIPTION
**Pull request by AhMohsen46**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 ! So once we have the sun letters this is good to go?

**Comment by ronaldtse** [comment]
@AhMohsen46 could you help check the original spec in https://github.com/interscript/interscript/issues/60#issuecomment-687987713 ? Thanks.

**Comment by AhMohsen46** [comment]
@ronaldtse will finish sun letters and check this now

**Comment by AhMohsen46** [comment]
@ronaldtse sun letters are now done and pushed

I guess it's good to be merged, I'll try in the next hour to start checking how to run it on our dataset to generate pointing from the transliterated words

only one thing required for all the previous arab maps
the issue for capitalizing the first letter of each word, there is a way to do it 
the exact same way like here https://github.com/interscript/interscript//blob/a95ee43317c08fdc775c3c5a09c381cc0a1affe1/maps/acadsin-zho-Hani-Latn-2002.yaml#L25
but it may take effort as we've more than the normal 26 english letters

or there is an easy work around, but may require a modification in here
https://github.com/interscript/interscript//blob/22600b4f383643966058818fc0cbd9a79b5eb610/lib/interscript.rb#L109

that I condition on the result

if result == "upcase"
I convert the letter to upcase and that's it, would be optimum I guess

**Comment by ronaldtse** [comment]
Thank you @AhMohsen46 ! Merging.

**Comment by AhMohsen46** [comment]
Great, Thanks @ronaldtse

**Pull request merged**
