### PR TITLE
Add Korean maps

### PR DESCRIPTION
**Pull request by chaaklau**
Adding three maps:

#122 Korean Ministry of Culture and Tourism 2000 System, 
#123 BGN Agreement -- Korean McCune-Reischauer System (1943), 
and a Hangul to Jamo map.

The first two maps work in a similar manner: 
1. Hangul is mapped to an intermediate romanisation (`#` is used in the MOCT map and `’` is added after n and h as delimiter)
2. There are pre-mapping rules that translate numerals (1-9) into Hangul and insert hyphens before generics. (The list of generics may need further revision.)
3. After character mapping, orthographic / phonological transformation is handled by post-rules.

Most of the required transformation is deterministic. There are some unpredictable sound changes (e.g. palatalisation of intervocalic /t'/ and insertion of /ng/), which cannot be handled by these maps.

These maps have been tested against GeoNames data. Other than the unhandled exceptions, the maps should be good for names without space or generics.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@chaaklau in the Jamo map, I see direct maps from Hangul to Hangul. Is the target supposed to be decomposed Jamo?

**Comment by chaaklau** [comment]
> Is the target supposed to be decomposed Jamo?

Yes, the target is "decomposed Jamo". I am not sure if this should be considered to be a subset of Hangul, or an independent script.

**Comment by ronaldtse** [comment]
> Yes, the target is "decomposed Jamo". I am not sure if this should be considered to be a subset of Hangul, or an independent script.

Somehow I'm not seeing the "decomposed Jamo" in the map... For sure it's a subset of Hangul but using `Hang` is not illustrative of what it is. (e.g. Hang-Hang is not meaningful.)

**Comment by chaaklau** [comment]
> Somehow I'm not seeing the "decomposed Jamo" in the map... 

Some browsers / apps render decomposed Jamo back into Hangul. On my Sublime, the file looks like this:
image

> For sure it's a subset of Hangul but using `Hang` is not illustrative of what it is. (e.g. Hang-Hang is not meaningful.)

Hang-Hang is not intuitive, but perhaps there are cases where the source and destination script is the same script, e.g. Between two versions of Cyrillic scripts for the same language, or like conversions between two transliteration systems (e.g. Jyutping <-> Yale)?

I don't have a strong opinion on this, I am happy to change it to Hang-Jamo if that looks better.

**Comment by ronaldtse** [comment]
You're right, the decomposed characters show in Vim but not in TextMate. No changes needed.

> Hang-Hang is not intuitive, but perhaps there are cases where the source and destination script is the same script, e.g. Between two versions of Cyrillic scripts for the same language, or like conversions between two transliteration systems (e.g. Jyutping <-> Yale)?

Good point. In Unicode they also have a chart that converts Latin characters into ASCII (which we should do too). That's technically Latn-Latn. Let's keep Hang-Hang-jamo.

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
