### PR TITLE
Add two maps for Cantonese

### PR DESCRIPTION
**Pull request by chaaklau**
Two maps have been added for Cantonese. ( #39 )

**hk-yue-Hant-Latn-govt**: Hong Kong Government Cantonese Romanisation (Loose Governmental Transliteration, **govt** in short)
**hk-yue-Hant-Latn-lshk**: LSHK Jyutping

The map for **govt** was generated from the LSHK Jyutping list in two steps:
1. **add archaic phonemic distinctions, which can be found in 《英華分韻撮要》**
e.g. the distinction between 張(cheung) and 將(tseung), 峽(hap) and 合(hop)

2. **symbol conversion**

Some manual adjustments were made to the **govt** list
- 徑: Add Keng (*King* was replaced by *Keng* probably to avoid confusion with the English word)
- 麖: Change King into Keng
- 嶼: Rank Yue > Tsui
- 孖: Rank Ma > Tsz
- 稔: Rank Nim, Lim > Nam, Lam
- 四: Rank Sze > Sei (The former is way more common in place names)
- 輋: Add Che (Missing pronunciation)
- 索: Change Shok into Sok

## Test results

1342 examples selected from the GeoNames dataset were tested, 167 failures. 
The failed cases are due to 
1. **typos in the original GeoNames dataset** (e.g. the character "涌" is incorrectly converted to "湧", "Siu Lam" incorrectly recorded as "Sui Lam", etc.)
2. **pronunciation variants** (e.g. 嶺 can be either leng or ling), or 
3. **non CJK characters ** (e.g. Bopomofo symbol ㄚ was used instead of TC character 丫).

See [govt-test.log](https://github.com/riboseinc/interoperable-transliteration/files/4031124/govt-test.log) for details.

## Remaining issues
1. I noticed that a character on Plane-2 (CJK Ext. B) was not mapped:
`    "\u220C7": "Lei " #𢃇`
Further investigation is needed.

**Update:** This is probably an issue with YAML.load_file(): unicode scalar > 0xFFFF will fail. Changing the line to `    "𢃇": "Lei " #𢃇` will fix the issue.

2. I added a space to all entries to the right. We will need a way to trim the trailing space, and perhaps also a parameter stating whether a space or other delimiter is needed for each transliteration scheme.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @chaaklau for the amazing work!

Since the files are too long GitHub doesn't let me comment:

1. The `hk-yue-Hant-Latn-lshk` map should be renamed to `lshk-yue-Hant-Latn-jyutping`. The `id:` should be changed to `jyutping`

2. Do we have the corresponding `Hans` => `Hant` maps? We probably don't want them as separate transliteration maps. Maybe we have a definitive, separate `Hans` => `Hant` mapping (which is not technically related to transliteration) which allows us to transliterate `Hans => Hant => Jyutping`?

Regarding "added a space to all entires to the right", do you want to remove that trailing space? I think the map characters should not have the trailing space -- the space is part of the scheme but not of the character mapping. We can probably add an option for that. (ping @abunashir )

**Comment by chaaklau** [comment]
1. Thanks, I will fix the file name and the meta.

2. In fact I included both Hans and Hant characters in this map, since the source list from OGCIO did not separate the two, and the two sets are highly overlapping anyway. I do have conversion tables (from Unihan) for Hans<->Hant if needed. Perhaps I should change “script” to “Han” to cover both TC and SC?

3. Speaking of which, I have not dealt with proper name capitalisation either. I capitalised the first letter for govt for now, but I think this logic should be moved elsewhere.

**Comment by ronaldtse** [comment]
> 2. In fact I included both Hans and Hant characters in this map, since the source list from OGCIO did not separate the two, and the two sets are highly overlapping anyway. I do have conversion tables (from Unihan) for Hans<->Hant if needed. Perhaps I should change “script” to “Han” to cover both TC and SC?

Got it. `Han` would make it more clear, indeed!

Perhaps right now we don't need the conversion tables yet... let's see if it's needed later.

> 3. Speaking of which, I have not dealt with proper name capitalisation either. I capitalised the first letter for govt for now, but I think this logic should be moved elsewhere.

Probably this should be an option? This sounds like a "proper noun => capitalize" rule.

**Comment by ronaldtse** [comment]
@chaaklau I'd like to let you know that the the `NAME_LINK` column (column AF) links the Non-Romanized and the Romanized entries. So it would be easy to filter them out.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @chaaklau ! Merging first, and posting the remaining issues as new ones.

**Pull request merged**
