### PR TITLE
Add more tests icao-bel-Cyrl-Latn-9303

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@CAMOBAP feel free to merge once the tests are moved to the PR for the new issue #308 . Thanks!

**Comment by ronaldtse** [comment]
Ping @CAMOBAP can we move these tests to #308 and merge this? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse I propose to close this one because I added test data based on real passports. But later I have found out they belong to `mvd-[bel|rus]-Cyrl-Latn` and not to `icao-*`

P.S. yep those tests will be moved to #308

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Pull request closed without merging**
