### PR TITLE
#137 add bgnpcgn-ron-cyrl-latn-2002

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #137

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP seems that the CI isn't running. Could you help reactivate it? Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP we're not supposed to need pytorch to run CI?

**Comment by CAMOBAP** [comment]
> we're not supposed to need pytorch to run CI?

locally it works without it, I'm trying to figure out why we need it at all

**Comment by CAMOBAP** [comment]
@ronaldtse well, CI works more or less:
 - windows blocked because https://github.com/sqreen/ruby-libv8-node/issues/9
 - macOS some tests failed will be investigated in the scope of https://github.com/interscript/interscript/issues/705

`bgnpcgn-ron-cyrl-latn-2002` passed, so I propose to merge this one

**Pull request merged**
