### PR TITLE
#315 Automate release based on tag

### PR DESCRIPTION
**Pull request by CAMOBAP**
Release to rubygems.org based on `git tag`

 - #315

### CODE REVIEW

**Comment by ronaldtse** [comment]
Seems to be failing on all Windows builds.

**Comment by CAMOBAP** [comment]
@ronaldtse something wrong with swig installation probably wrong or missing SWIG_LIB environment variable, checking this

**Comment by CAMOBAP** [comment]
@ronaldtse fixed after the downgrade, I have contacted with the maintainer of swig package on chocolatey

**Comment by CAMOBAP** [comment]
@ronaldtse @phuonghuynh could you please review/approve this PR

**Review by phuonghuynh — APPROVED** [review]
LGTM

**Comment by phuonghuynh** [comment]
@ronaldtse need your help on set up GHA secrets for deploying to RubyGems, https://github.com/interscript/interscript/runs/922523256?check_suite_focus=true

**Comment by ronaldtse** [comment]
@phuonghuynh added INTERSCRIPT_RUBYGEMS_API_KEY key now.

**Pull request merged**
