### PR TITLE
Add Bengali systems (UN and ALA-LC)

### PR DESCRIPTION
**Pull request by ronaldtse**
This is for @abunashir .  The system is located here:

http://www.eki.ee/wgrs/rom1_bn.htm
http://www.eki.ee/wgrs/rom1_bn.pdf

There are these issues:

1. 
```
    # V. Ligatures
    # Adscript forms of some consonants
    'র্‍':	'r-:'
    '‍্র':	'-r:'
    '‍্য':	'-y:'
```

These don't work because these have to be a "pattern" rule. (see other maps)

2. In general, not sure if it works with real Bengali. There is no provided text in Bengali for testing.

@abunashir given your literacy in this language, could you help make this work? Thanks!

### CODE REVIEW

**Comment by abunashir** [comment]
These are the tricky ones, I can think of a couple of words on top of my head, but I'm not sure if there is a definitive pattern since there are a couple of letters before and after can produce sound. I will have to look through some grammar and see if I can find some definitive answers.

> There are these issues:
> 
> 
> ```
>     # V. Ligatures
>     # Adscript forms of some consonants
>     'র্‍':	'r-:'
>     '‍্র':	'-r:'
>     '‍্য':	'-y:'
> ```
> 
> These don't work because these have to be a "pattern" rule. (see other maps)
> 

I don't read roman, but from the sound of it, it seems to be pretty close, let me add some sample text and let's see if that can be transformed back and forth between the input and output.

> 1. In general, not sure if it works with real Bengali. There is no provided text in Bengali for testing.

**Comment by ronaldtse** [comment]
@abunashir thanks, will wait for you to provide some real Bengali text and some "human transliterated" samples .

To make sure Bengali transliteration works for different systems, I've added another one to this PR, the ALA-LC Bengali Romanization system:
https://www.loc.gov/catdir/cpso/romanization/bengali.pdf

They will be good comparisons in testing.

**Comment by abunashir** [comment]
Hi @ronaldtse, I could not find exact documentation for these rules, but I had a look on couple of opensource project about it and let me try to explain if this helps, normally `র্‍` is `ra` but if it is at the end of a word then we normally omit the `a`, and only use `r`.
>     'র্‍':	'r-:'

For this, I think we don't need a separate rule,  normally there are a couple of constant it can combines to, and those are already added as separate mappings, like: `'গ্র': 'gra'`, `'ঘ্র': 'ghra'`, `'প্র': 'pra'`, `'ফ্র': 'phra'` and etc.

>     '‍্র':	'-r:'

This one is normally positioned at the end of a word, and normally translate to `y`, so I think a normal mapping with this `y` should work fine. 
>     '‍্য':	'-y:'

So, I think we can go with this kind of pattern for now, I will put together a pull request soon, let me know if you would like to add anything else here.

**Comment by ronaldtse** [comment]
Thanks @abunashir for clarifying. For this rule:

```
'র্‍':	'r-:'
```

The example they gave was: `র্ক rka` (unicode: `\u09b0\u09cd\u0995`), composed of:
* `র্` (unicode: `\u09b0\u09cd`) and
* `ক ka` (unicode: `\u0995`)

I guess that meant adding an "r" in the beginning of the word if the word starts with `র্`?

On the other hand, `'গ্র': 'gra'`, `'ঘ্র': 'ghra'`, `'প্র': 'pra'`, `'ফ্র': 'phra'`: do we need to drop the "a" at the end if they are at the end of the word?

**Comment by abunashir** [comment]
Yap, ideally if any words combine `র্` with any constant then it will start an `r`, but there are still some exceptions though. For example, for `তর্ক`, you would write something like `torkha`, but in this case, the r will still come before those actual sounding constant, but maybe not the whole word.

> I guess that meant adding an "r" in the beginning of the word if the word starts with `র্`?

No, for this one we don't drop `a` from the end, but any other words end with `র্‍ `, normally drops the `a`, from `ra`.

> On the other hand, 'গ্র': 'gra', 'ঘ্র': 'ghra', 'প্র': 'pra', 'ফ্র': 'phra': do we need to drop the "a" at the end if they are at the end of the word?

**Comment by abunashir** [comment]
Actually, I was looking into these combined letters, but it seems like it might be pretty hard to form rules, But found a list of 286 (commonly used combined) letters, should we start with a literal mapping for this combined letter for now? source: https://www.somewhereinblog.net/blog/trivuzblog/28849694

**Comment by abunashir** [comment]
I went through the whole list, the good news is, the [UN Romanization site]( http://www.eki.ee/wgrs/rom1_bn.htm) already did the mapping for 130+ combined letters and those seem to be pretty accurate. Here are the remaining ones we would have to do it manually. Once, this are done then I think we won't need to define rules or pattern for this anymore.

```
 3. ক্ট্র = ক + ট + র; যেমন- অক্ট্রয়
 5. ক্ত্র = ক + ত + র; যেমন- বক্ত্র
 8. ক্য = ক + য; যেমন- বাক্য
 12. ক্ষ্ণ = ক + ষ + ণ; যেমন- তীক্ষ্ণ
 14. ক্ষ্ম = ক + ষ + ম; যেমন- লক্ষ্মী
 18. খ্য = খ + য; যেমন- সখ্য
 19. খ্র = খ+ র যেমন; যেমন- খ্রিস্টান
 20. গ্‌ণ = গ + ণ; যেমন - রুগ্‌ণ
 22. গ্ধ্য = গ + ধ + য; যেমন- বৈদগ্ধ্য
 23. গ্ধ্র = গ + ধ + র; যেমন- দোগ্ধ্রী
 25. গ্ন্য = গ + ন + য; যেমন- অগ্ন্যাস্ত্র, অগ্ন্যুৎপাত, অগ্ন্যাশয়
 26. গ্ব = গ + ব; যেমন- দিগ্বিজয়ী
 28. গ্য = গ + য; যেমন- ভাগ্য
 30. গ্র্য = গ + র + য; যেমন- ঐকাগ্র্য, সামগ্র্য, গ্র্যাজুয়েট
 32. ঘ্ন = ঘ + ন; যেমন- কৃতঘ্ন
 33. ঘ্য = ঘ + য; যেমন- অশ্লাঘ্য
 36. ঙ্‌ক্ত = ঙ + ক + ত; যেমন- পঙ্‌ক্তি
 37. ঙ্ক্য = ঙ + ক + য; যেমন- অঙ্ক্য
 38. ঙ্ক্ষ = ঙ + ক + ষ; যেমন- আকাঙ্ক্ষা
 39. ঙ্খ = ঙ + খ; যেমন- শঙ্খ
 41. ঙ্গ্য = ঙ + গ + য; যেমন- ব্যঙ্গ্যার্থ, ব্যঙ্গ্যোক্তি
 42. ঙ্ঘ = ঙ + ঘ; যেমন- সঙ্ঘ
 43. ঙ্ঘ্য = ঙ + ঘ + য; যেমন- দুর্লঙ্ঘ্য
 44. ঙ্ঘ্র = ঙ + ঘ + র; যেমন- অঙ্ঘ্রি
 45. ঙ্ম = ঙ + ম; যেমন- বাঙ্ময়
 49. চ্ছ্র = চ + ছ + র; যেমন- উচ্ছ্রায়
 51. চ্ব = চ + ব; যেমন- চ্বী
 52. চ্য = চ + য; যেমন- প্রাচ্য
 58. জ্য = জ + য; যেমন- রাজ্য
 59. জ্র = জ + র; যেমন- বজ্র
 65. ট্ব = ট + ব; যেমন- খট্বা
 66. ট্ম = ট + ম; যেমন- কুট্মল
 67. ট্য = ট + য; যেমন- নাট্য
 68. ট্র = ট + র; যেমন- ট্রেন (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
 70. ড্ব = ড + ব; যেমন- অন্ড্বান
 71. ড্য = ড + য; যেমন- জাড্য
 72. ড্র = ড + র; যেমন- ড্রাইভার, ড্রাম (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
 73. ড়্গ = ড় + গ; যেমন- খড়্‌গ
 74. ঢ্য = ঢ + য; যেমন- ধনাঢ্য
 75. ঢ্র = ঢ + র; যেমন- মেঢ্র (ত্বক) (মন্তব্য: অত্যন্ত বিরল)
 78. ণ্ঠ্য = ণ + ঠ + য; যেমন- কণ্ঠ্য
 80. ণ্ড্য = ণ + ড + য; যেমন- পাণ্ড্য
 81. ণ্ড্র = ণ + ড + র; যেমন- পুণ্ড্র
 82. ণ্ঢ = ণ + ঢ; যেমন- ষণ্ঢ
 83. ণ্ণ = ণ + ণ; যেমন- বিষণ্ণ
 84. ণ্ব = ণ + ব; যেমন- স্হাণ্বীশ্বর
 85. ণ্ম = ণ + ম; যেমন- চিণ্ময়
 86. ণ্য = ণ + য; যেমন- পূণ্য
 87. ৎক = ত + ক; যেমন- উৎকট
 90. ত্ত্য = ত + ত + য; যেমন- উত্ত্যক্ত
 95. ত্ম্য = ত + ম + য; যেমন- দৌরাত্ম্য
 96. ত্য = ত + য; যেমন- সত্য
 98. ত্র্য = ত + র + য; যেমন- বৈচিত্র্য
 99. ৎল = ত + ল; যেমন- কাৎলা
100. ৎস = ত + স; যেমন- বৎসর, উৎসব
101. থ্ব = থ + ব; যেমন- পৃথ্বী
102. থ্য = থ + য; যেমন- পথ্য
103. থ্র = থ + র; যেমন- থ্রি (three) (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
104. দ্গ = দ + গ; যেমন- উদ্গম
105. দ্ঘ = দ + ঘ; যেমন- উদ্ঘাটন
111. দ্ভ্র = দ + ভ + র; যেমন- উদ্ভ্রান্ত
113. দ্য = দ + য; যেমন- বাদ্য
115. দ্র্য = দ + র + য; যেমন- দারিদ্র্য
116. ধ্ন = ধ + ন; যেমন- অর্থগৃধ্নু
117. ধ্ব = ধ + ব; যেমন- ধ্বনি
118. ধ্ম = ধ + ম; যেমন- উদরাধ্মান
119. ধ্য = ধ + য; যেমন- আরাধ্য
121. ন্ট = ন + ট; যেমন- প্যান্ট (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
122. ন্ট্র = ন + ট + র; যেমন- কন্ট্রোল (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
125. ন্ড্র = ন + ড + র; যেমন- হান্ড্রেড
127. ন্ত্ব = ন + ত + ব; যেমন- সান্ত্বনা
128. ন্ত্য = ন + ত + য; যেমন- অন্ত্য
130. ন্ত্র্য = ন + ত + র + য; যেমন- স্বাতন্ত্র্য
132. ন্থ্র = ন + থ + র; যেমন- অ্যান্থ্রাক্স (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
134. ন্দ্য = ন + দ + য; যেমন- অনিন্দ্য
135. ন্দ্ব = ন + দ + ব; যেমন- দ্বন্দ্ব
138. ন্ধ্য = ন + ধ + য; যেমন- বিন্ধ্য
139. ন্ধ্র = ন + ধ + র; যেমন- রন্ধ্র
143. ন্য = ন + য; যেমন- ধন্য
144. প্ট = প + ট; যেমন- পাটি-সাপ্টা, ক্যাপ্টেন (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
148. প্য = প + য; যেমন- প্রাপ্য
150. প্র্য = প + র + য; যেমন- প্র্যাকটিস (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
152. প্স = প + স; যেমন- লিপ্সা
154. ফ্ল = ফ + ল; যেমন- ফ্লেভার (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
159. ব্য = ব + য; যেমন- দাতব্য
161. ব্ল = ব + ল; যেমন- ব্লাউজ
162. ভ্ব =ভ + ব; যেমন- ভ্বা
163. ভ্য = ভ + য; যেমন- সভ্য
165. ম্ন = ম + ন; যেমন- নিম্ন
167. ম্প্র = ম + প + র; যেমন- সম্প্রতি
168. ম্ফ = ম + ফ; যেমন- লম্ফ
170. ম্ব্র = ম + ব + র; যেমন- মেম্ব্রেন (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
174. ম্য = ম + য; যেমন- গ্রাম্য
177. য্য = য + য; যেমন- ন্যায্য
178. র্ক = র + ক; যেমন - তর্ক
179. র্ক্য = র + ক + য; যেমন- অতর্ক্য (তর্ক দিয়ে যার সমাধান হয় না)
180. র্গ্য = র + গ + য; যেমন - বর্গ্য (বর্গসম্বন্ধীয়)
181. র্ঘ্য = র + ঘ + য; যেমন- দৈর্ঘ্য
182. র্চ্য = র + চ + য; যেমন- অর্চ্য (পূজনীয়)
183. র্জ্য = র + জ + য; যেমন- বর্জ্য
184. র্ণ্য = র + ণ + য; যেমন- বৈবর্ণ্য (বিবর্ণতা)
185. র্ত্য = র + ত + য; যেমন- মর্ত্য
186. র্থ্য = র + থ + য; যেমন- সামর্থ্য
187. র্ব্য = র + ব + য; যেমন- নৈর্ব্যক্তিক
188. র্ম্য = র + ম + য; যেমন- নৈষ্কর্ম্য
189. র্শ্য = র + শ + য; যেমন- অস্পর্শ্য
190. র্ষ্য = র + ষ + য; যেমন- ঔৎকর্ষ্য
191. র্হ্য = র + হ + য; যেমন- গর্হ্য
192. র্খ = র + খ; যেমন- মূর্খ
193. র্গ = র + গ; যেমন- দুর্গ
194. র্গ্র = র + গ + র; যেমন- দুর্গ্রহ, নির্গ্রন্হ
195. র্ঘ = র + ঘ; যেমন- দীর্ঘ
196. র্চ = র + চ; যেমন- অর্চনা
197. র্ছ = র + ছ; যেমন- মূর্ছনা
198. র্জ = র + জ; যেমন- অর্জন
199. র্ঝ = র + ঝ; যেমন- নির্ঝর
200. র্ট = র + ট; যেমন- আর্ট, কোর্ট, কম্ফর্টার, শার্ট, কার্টিজ, আর্টিস্ট, পোর্টম্যানটো, সার্টিফিকেট, কনসার্ট, কার্টুন, কোয়ার্টার (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
201. র্ড = র + ড; যেমন- অর্ডার, লর্ড, বর্ডার, কার্ড (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
202. র্ণ = র + ণ; যেমন- বর্ণ
203. র্ত = র + ত; যেমন- ক্ষুধার্ত
204. র্ত্র = র + ত + র; যেমন- কর্ত্রী
205. র্থ = র + থ; যেমন- অর্থ
206. র্দ = র + দ; যেমন- নির্দয়
207. র্দ্ব = র + দ + ব; যেমন- নির্দ্বিধা
208. র্দ্র = র + দ + র; যেমন- আর্দ্র
209. র্ধ = র + ধ; যেমন- গোলার্ধ
210. র্ধ্ব = র + ধ + ব; যেমন- ঊর্ধ্ব
211. র্ন = র + ন; যেমন- দুর্নাম
212. র্প = র + প; যেমন- দর্প
213. র্ফ = র + ফ; যেমন- স্কার্ফ (মন্তব্য: মূলত ইংরেজি ও আরবী-ফার্সি কৃতঋণ শব্দে ব্যবহৃত)
214. র্ভ = র + ভ; যেমন- গর্ভ
215. র্ম = র + ম; যেমন- ধর্ম
216. র্য = র + য; যেমন- আর্য
217. র্ল = র + ল; যেমন- দুর্লভ
218. র্শ = র + শ; যেমন- স্পর্শ
219. র্শ্ব = র+ শ + ব; যেমন- পার্শ্ব
220. র্ষ = র + ষ; যেমন- ঘর্ষণ
221. র্স = র + স; যেমন- জার্সি, নার্স, পার্সেল, কুর্সি (মন্তব্য: মূলত ইংরেজি ও আরবী-ফার্সি কৃতঋণ শব্দে ব্যবহৃত)
222. র্হ = র + হ; যেমন- গার্হস্থ্য
223. র্ঢ্য = র + ঢ + য; যেমন- দার্ঢ্য (অর্থাৎ দৃঢ়তা)
225. ল্ক্য = ল + ক + য; যেমন- যাজ্ঞবল্ক্য
226. ল্গ = ল + গ; যেমন- বল্গা
229. ল্প = ল + প; যেমন- বিকল্প
230. ল্‌ফ = ল + ফ; যেমন- গল্‌ফ (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
231. ল্ব = ল + ব; যেমন- বিল্ব, বাল্ব
232. ল্‌ভ = ল + ভ; যেমন- প্রগল্‌ভ
234. ল্য = ল + য; যেমন- তারল্য
241. শ্য = শ + য; যেমন- অবশ্য
245. ষ্ক্র = ষ + ক + র; যেমন- নিষ্ক্রিয়
247. ষ্ট্য = ষ + ট + য; যেমন- বৈশিষ্ট্য
250. ষ্ঠ্য = ষ + ঠ + য; যেমন- নিষ্ঠ্যূত
251. ষ্ণ = ষ + ণ; যেমন- কৃষ্ণ
253. ষ্প্র = ষ + প + র; যেমন- নিষ্প্রয়োজন
255. ষ্ব = ষ + ব; যেমন- মাতৃষ্বসা
256. ষ্ম = ষ + ম; যেমন- উষ্ম
257. ষ্য = ষ + য; যেমন- শিষ্য
261. স্ট = স + ট; যেমন- স্টেশন (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
262. স্ট্র = স + ট্র; যেমন- স্ট্রাইক (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
264. স্ত্ব = স + ত + ব; যেমন- বহিস্ত্বক
265. স্ত্য = স + ত + য; যেমন-অস্ত্যর্থ
266. স্ত্র = স + ত + র; যেমন- স্ত্রী
267. স্থ = স + থ; যেমন- দুঃস্থ
268. স্থ্য = স + থ + য; যেমন- স্বাস্থ্য
270. স্প = স + প; যেমন- আস্পর্ধা
271. স্প্র = স + প +র; যেমন- স্প্রিং (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
272. স্প্‌ল = স + প + ল; যেমন- স্প্‌লিন (মন্তব্য: এই যুক্তাক্ষরটি মূলত ইংরেজি/বিদেশী কৃতঋণ শব্দে ব্যবহৃত)
273. স্ফ = স + ফ; যেমন- আস্ফালন
276. স্য = স + য; যেমন- শস্য
278. স্ল = স + ল; যেমন- স্লোগান
279. হ্ণ = হ + ণ; যেমন- অপরাহ্ণ
281. হ্ব = হ + ব; যেমন- আহ্বান
283. হ্য = হ + য; যেমন- বাহ্য
286) হৃ = হ   ৃ ; যেমন- হৃদয়, ব্যবহৃত
```

Also, that site mentioned their combined letters list are still missing, so once this is done we might consider contributing back (only if they are interested).

cc: @ronaldtse

**Comment by abunashir** [comment]
Hi @ronaldtse: I've updated the mappings for the UN system, There are a couple of improvements we can do in the future but this should be able to transliterate most of the Bangla text. Please let me know if there is anything else on this one.

**Comment by ronaldtse** [comment]
@abunashir this is good!

Regarding the extra mappings found on the site:
```
 3. ক্ট্র = ক + ট + র; যেমন- অক্ট্রয়
 5. ক্ত্র = ক + ত + র; যেমন- বক্ত্র
...
```

Is there a way we can "generate" or "generalize" them?

Because we will need to confirm with the UN whether their system accepts these extra mappings. If we can "generalize" the original mapping rules from their system, which could generate these extra mappings, we can still be compliant with what they have defined.

Thanks!

**Comment by abunashir** [comment]
Actually, the list I've added is a combined rule build from their original mappings, let's take the first one for example, `ক্ট্র` it's a combination of `ক`, `ট` and `র`. If you literally map those letters to the UN system then it would be `ka`, `ṭa` and `ra`, All together: `kaṭara`.

But one important thing to consider here is when you combined multiple letters to form a combined letter then the first letter drops its sound, so that's why we write it as `kṭara`, the `a` dropped from the first letter. (Note: If it's 3 letters combination then I believe the second letter drops `a` sounds too, but I'm not 100% certain yet, still need to do some research on that).

If you look at existing ligatures provided by UN then you will find the same, for example, take this second one `ক্ট`, which is a combined letter of `ক` and `ট`, which literally would be `kaṭa`, but they mapped it as `kṭa`, the first letter dropped the `a`.

Screenshot 2019-12-10 at 16 16 27

do you think is it something we can use as a reference? @ronaldtse

**Comment by ronaldtse** [comment]
I think this works! At least for now. Can we specify this ligature mapping by a set of rules? It gives confidence that the mappings are correct. The current > 300 ligature map can be seen as a computed map from those rules?

**Comment by abunashir** [comment]
@ronaldtse: Yes, we certainly can, there are a couple of rules. But, the good news is I actually found a publication from Hanover University for  Sanskrit ligatures. Sanskrit is the root of Bangla and a couple of Indian languages. You can check the details here: [Sanskrit Alphabet](http://www.unics.uni-hannover.de/nhtcapri/sanskrit-alphabet.html)

So, at a high level I think we can sum this up as follows:
* For the Ligatures, first we need to identify what are the letters they are made of.
* Once we have those letters identified, then we can do a literal mapping of those letters
* But since Ligatures is a combination for a couple of letters so when we combine them some letters drop some sounds, and we can describe it as:
  - If it's two letters combination then only the first letter drops its last letter mostly it's `a`.
  - If it's three or more letters combination then each letter drop sounds except the last one.

* There are a couple of exceptions like`'‍্` and `'‍্য'`, for this we use the mapping from the UN documents.


Interesting read: https://www.newworldencyclopedia.org/entry/bengali_language

**Comment by abunashir** [comment]
There were a couple of changes necessary to comply with that publication but just updated the mappings, we should be good to go now. Let me know if there is anything else.

**Comment by ronaldtse** [comment]
Thanks @abunashir ! Last thing -- could you help add a test for the `alalc` system just like for the `un` system? That would ensure we get things right. After adding the test feel free to merge. Thanks!

**Comment by abunashir** [comment]
@ronaldtse: If I understand correctly, we don't have any character mappings (apart from the core vowels, and consonants) for `alalc`.  Do you want me to find/write all other mappings including ligatures and then add the tests? Or we can reuse the ones from UN system?

**Comment by ronaldtse** [comment]
@abunashir sorry for the late reply. You are correct, we only have the information from [this file](https://www.loc.gov/catdir/cpso/romanization/bengali.pdf) . There are two approaches:
1. Write out all mappings including ligatures
2. "Program" those mappings into the YAML file using some rules

What do you think?

**Comment by ronaldtse** [comment]
@abunashir ping, there are some tests that are failing. Thanks.

**Comment by abunashir** [comment]
Cool, I will start looking into it now, but I will create a separate pull request with your changes for alalc.

**Comment by abunashir** [comment]
@ronaldtse: The failing tests were related to the Mongolian mappings, so I've added a temporary rule to keep the test suite green, I will merge this one now, but I will also create an issue with that todo, do we have any natives that might help us out with the Mongolian mappings?

**Comment by ronaldtse** [comment]
@abunashir that's absolutely fine. Let me find out about Mongolian -- maybe we should keep that as a separate PR...

**Comment by abunashir** [comment]
Yap, I merged the one for now with an opened issue, I hope that's okay 😉

**Pull request merged**
