### PR TITLE
Added BGNPCGN Modern Syriac map 2011

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
Hi Ron,

I have several transliterations set already. But I'd like you to review this one to see if I'm on track.

Thanks!

### CODE REVIEW

**Review by andrew2net — COMMENTED** [review]
We need to define at least one test case for each transliteration system. Please add `source` and `expected` in the `test` section.

**Comment by ronaldtse** [comment]
> We need to define at least one test case for each transliteration system. Please add source and expected in the test section.

Right, but it seems that the source reference doesn't provide any examples. Will need to find them...

**Comment by AhMohsen46** [comment]
@ronaldtse related [doc](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693736/ROMANIZATION_OF_MODERN_SYRIAC.pdf) is having arabic equivalents, but it's not basically arabic, I -unforunately- don't think I can do this
however, if we had no other option I may do a little bit of exploration and transliterate the 22 letter language as per the doc, but I can't guarantee a 100% of success and test coverage

**Comment by ronaldtse** [comment]
Replaced with https://github.com/interscript/maps/pull/167.

**Pull request closed without merging**
