### PR TITLE
added un-nep-deva-latn-2013

### PR DESCRIPTION
**Pull request by bilashsaha**

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Good to go once the tests pass. Thanks!

**Comment by bilashsaha** [comment]
@ronaldtse  We are facing test failure due to 
```
bundler: command not found: spec
Ins`tall missing gem executables with `bundle install
```

and may be because of [this](https://github.com/interscript/interscript/commit/2f7913501e32d8f0a890e0a6e16f5134658cccf9) commit ?

**Comment by ronaldtse** [comment]
Sorry that was poor pushing on my side. Can you rebase? Thanks!

**Comment by ronaldtse** [comment]
Thank you @bilashsaha !

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/427

**Pull request merged**
