### PR TITLE
Add "word_separator" and a "title_case" option

### PR DESCRIPTION
**Pull request by chaaklau**
Add `word_separator` mapping to allow a different character for word-boundary marking (see also #201 ).

`historic-zho-Hani-Latn-1979`
Example: The last character of`玉蓮寺` is a generic item, and the name is supposed to be divided into two parts: `玉蓮|寺`. In this system, character-boundaries are indicated by dashes, and word boundaries (including generics) are indicated by a space. The correct rendering is `Yü-lien Ssu`.

With just one separator key, we can only get either `Yü-lien-ssu` or  `Yü Lien Ssu`. This has been fixed by setting `word_separator` as a space, and `character_separator` as a dash. 

This commit also adds `title_case` mapping, a boolean value which indicates whether the first character of a word needs to be capitalised.

```
map:
  character_separator: "-"
  word_separator: " "
  title_case: true
```

Mapping rules for `hk-yue-Han-Latn-govt.yaml` have also been updated to improve readability of the map, and fix other minor data issue.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Looks good to me. Thanks @chaaklau!

**Comment by ronaldtse** [comment]
The option "`title_case` works for the target scripts or Latn and Cyrl, but not some others, eg if we want to transliterate into Hant. We can keep the option name for name but wonder if there is a language-independent way of saying “title case”?

**Comment by chaaklau** [comment]
> wonder if there is a language-independent way of saying “title case”?

I think `title_case` parameter has to be script-specific: it is only relevant when used with a target script that makes an upper-lower case distinction, but it will be language-independent (no matter what language it is, the script is language-agnostic, all first letters will be capitalised).

Perhaps as an enhancement we can add a separate option (`proper_nouns`, `proper_names` or just `names`), but that would be a language-specific option that transliterate input using name-specific rules / segmentation strategies.

**Comment by ronaldtse** [comment]
> I think title_case parameter has to be script-specific: it is only relevant when used with a target script that makes an upper-lower case distinction, but it will be language-independent (no matter what language it is, the script is language-agnostic, all first letters will be capitalised).

Agree. The "title case" feature is script specific.

`proper_names` is transliteration-system specific (and therefore bound to script/language too) -- some transliteration systems don't even define proper names.

**Pull request merged**
