### PR TITLE
Implement PyCall + Sequitur for Thai transcription and Fix dictionary-lookup

### PR DESCRIPTION
**Pull request by chaaklau**
Using PyCall + Sequitur and data from Wiktionary to implement Thai maps.

Python 3.7+ and following dependencies are needed.
```
pip3 install numpy
pip3 install git+https://github.com/sequitur-g2p/sequitur-g2p@master
```

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 could you please help fix GHA for Ubuntu and Windows? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse moved to own fork `git+https://github.com/CAMOBAP795/sequitur-g2p@master` I hope they will accept my PR soon https://github.com/sequitur-g2p/sequitur-g2p/pull/58

**Comment by ronaldtse** [comment]
Thanks @chaaklau and @CAMOBAP795 !

@CAMOBAP795 do we need to update sequitur here to use the newly merged fix?

**Comment by CAMOBAP** [comment]
@ronaldtse this is how we installed `sequitur-g2p` initially `pip3 install git+https://github.com/sequitur-g2p/sequitur-g2p@master`, so because my PR was accepted we don't change anything

P.S. to be honest for me it a bit scary install module from master each time, maybe it makes sense to use a specific commit instead of `master`

@ronaldtse @chaaklau any thoughts about this?

**Comment by ronaldtse** [comment]
@CAMOBAP795 we can just use the latest commit 806273f ? 

Instead of pip install using git we can also download the zip and use `pip install {filename}.zip` (https://github.com/sequitur-g2p/sequitur-g2p/archive/806273f.zip).

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@CAMOBAP795 please update the pip setup method and merge this directly. Thanks!

**Comment by CAMOBAP** [comment]
> Instead of pip install using git we can also download the zip and use `pip install {filename}.zip` (https://github.com/sequitur-g2p/sequitur-g2p/archive/806273f.zip).

@ronaldtse good point but because we use one CI configuration for all platforms so I propose to keep  installation with `git+https://github.com/sequitur-g2p/sequitur-g2p@806273f`

For users, I agree that we can install it with `pip install {filename}.zip `

@ronaldtse I have updated README too, could you please check

**Comment by ronaldtse** [comment]
Merging now. Thank you guys!

**Pull request merged**
