### PR TITLE
Ft arabic sunletters transliteration

### PR DESCRIPTION
**Pull request by AhMohsen46**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@AhMohsen46 very strange, the tests are failing on macOS rubies (Windows Ruby 2.6 failure was a network issue) because of this spec:
```
  1) Interscript maps/un-ara-Arab-Latn-2017.yaml system test for {"source"=>"السُعُودِية", "expected"=>"as su‘ūdīyah"}
     Failure/Error: expect(result).to eq(expected)

       expected: "as su‘ūdīyah"
            got: "as su‘ūwdīyah"

       (compared using ==)
     # ./spec/interscript_spec.rb:20:in `block (6 levels) in <top (required)>'
     # ./spec/interscript_spec.rb:17:in `block (5 levels) in <top (required)>'

Finished in 43.36 seconds (files took 3.27 seconds to load)
3634 examples, 1 failure

Failed examples:

rspec ./spec/interscript_spec.rb[1:71:7] # Interscript maps/un-ara-Arab-Latn-2017.yaml system test for {"source"=>"السُعُودِية", "expected"=>"as su‘ūdīyah"}
```

But it works on all other platforms...?

**Comment by AhMohsen46** [comment]
@ronaldtse  Might it be a specific encoding issue in these versions?, not sure, will have it the first on my list today
the rule that may cause that is having
"damma", before "و"
'\u064f\u0648' : 'ū'  # ـُو damma followed by و
if we splitted '\u064f\u0648' result would be `u,w` but not `ū,w`
however, we've the exact same case in sudan
  - source: السُودان
    expected: as sūdān

I suspect it might be something related to having عُ before و
because 
'\u0639\u064f' : '‘ū'    `عُ`
and
'\u064f\u0648' : 'ū'    `ـُو`

are intersecting in `\u064f`

on a second thought, strange it worked on ubuntu tho, the only case that may make this happen is if the word or the hash are iterated in different patterns in mac than in ubuntu
I'm 100% certain this will work on in case the regex matching in ubuntu is matching the whole arabic string everytime, not updating the text -- separating output from input not doing the replaces while transliterating the input, which I guess is not the case   
I can have this working with a regex detecting the preceding letter, but I find it interesting to look into before doing the fix, maybe I'll contribute to ubuntu :'D

**Comment by ronaldtse** [comment]
This is clearly an inconsistency in the Ruby usage of regular expressions (perhaps due to libpcre). Ubuntu and Windows have same behavior but macOS matches differently... Maybe it is to be filed with Apple or libpcre?

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @AhMohsen46 !

**Pull request merged**
