### PR TITLE
#75 (BGN/PCGN Romanization System -- Belarusian (1979) bgnpcgn-bel-cyrl-latn-1979

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #75

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Should we enable the optional rules here? Or is the data in #75 not using the optional rules?

**Comment by CAMOBAP** [comment]
@ronaldtse good point, enabled

**Comment by ronaldtse** [comment]
Seems to be failing on Windows 2.5:

```
Installing the following packages:
6
swig
7
By installing you accept licenses for the packages.
8
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
9
 Unable to connect to the remote server
10
swig not installed. The package was not found with the source(s) listed.
11
 Source(s): 'https://chocolatey.org/api/v2/'
12
 NOTE: When you specify explicit sources, it overrides default sources.
13
If the package version is a prerelease and you didn't specify `--pre`,
14
 the package may not be found.
15
Please see https://chocolatey.org/docs/troubleshooting for more 
16
 assistance.
17

18
Chocolatey installed 0/1 packages. 1 packages failed.
19
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
20

21
Failures
22
 - swig - swig not installed. The package was not found with the source(s) listed.
23
 Source(s): 'https://chocolatey.org/api/v2/'
24
 NOTE: When you specify explicit sources, it overrides default sources.
25
```

**Comment by ronaldtse** [comment]
All passing now.

**Pull request merged**
